### ISSUE TITLE
On follow: Cannot read property '__typename' of undefined

### ISSUE THREAD

**Issue by Banonevar** [dlive-apis/dlivetv-api-js#12]
**Describe the bug**
Got this on follow:
```
TypeError: Cannot read property '__typename' of undefined
    at WebSocketConnection.<anonymous> (D:\Projects\bot\node_modules\dlivetv-unofficial-api\src\index.js:72:55)
    at WebSocketConnection.emit (events.js:193:13)
    at WebSocketConnection.processFrame (D:\Projects\bot\node_modules\websocket\lib\WebSocketConnection.js:554:26)
    at D:\Projects\bot\node_modules\websocket\lib\WebSocketConnection.js:323:40
    at processTicksAndRejections (internal/process/task_queues.js:79:9)
```

**To Reproduce**
I used it like
```javascript
this.client.on('ChatFollow', async (object) => {
      await db.insert('events', { type: 'follow', username: object.sender.displayname })
})
```
**Expected behavior**

**Screenshots**

**Development runtime (please complete the following information):**
 - dlive 2.1.18

**Additional context**

**Comment by Banonevar** [comment]
Or maybe it was not on follow event, i'm not exactly sure. But i just clicked `follow` from my fake account for test, and bot was crashed with that error.

**Comment by Carbowix** [comment]
Hot fix will be released to fix some issues, stay tuned.
